-- MySQL Script generated by MySQL Workbench
-- Mon Mar 18 13:05:03 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema topicos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema topicos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `topicos` DEFAULT CHARACTER SET utf8 ;
USE `topicos` ;

-- -----------------------------------------------------
-- Table `topicos`.`pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `topicos`.`pessoa` (
  `idpessoa` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(60) NULL,
  `nome` VARCHAR(45) NULL,
  `sobrenome` VARCHAR(100) NULL,
  `datanasc` DATE NULL,
  PRIMARY KEY (`idpessoa`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `topicos`.`pesquisas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `topicos`.`pesquisas` (
  `idpesquisa` INT NOT NULL,
  `titulopesquisa` VARCHAR(45) NOT NULL,
  `descpesquisa` LONGTEXT NULL,
  PRIMARY KEY (`idpesquisa`),
  UNIQUE INDEX `titulopesquisa_UNIQUE` (`titulopesquisa` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `topicos`.`questoes_pesquisas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `topicos`.`questoes_pesquisas` (
  `idpesquisa` INT NOT NULL,
  `idquestao` INT NOT NULL,
  `descquestao` LONGTEXT NOT NULL,
  INDEX `fk_questionário_pesquisas_pesquisas_idx` (`idpesquisa` ASC) VISIBLE,
  PRIMARY KEY (`idpesquisa`, `idquestao`),
  CONSTRAINT `fk_questionário_pesquisas_pesquisas`
    FOREIGN KEY (`idpesquisa`)
    REFERENCES `topicos`.`pesquisas` (`idpesquisa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
